# Setup
title:               SEAStats
description:         Stats and data science learning resources for researchers in the USDA ARS Southeast Area
url:                 https://qdread.github.io/SEAstats
color-scheme:        dark
favicon:             true

# About/contact
author:
  name:              Quentin Read
  url:               https://quentinread.com
  email:             quentin.read@usda.gov

remote_theme:        vaibhavvikas/jekyll-theme-minimalistic
plugins:
  - jekyll-remote-theme
  - jekyll-redirect-from

github:
  repo:              https://github.com/qdread/SEAStats
  
navigation:
  - name: SEAStats Home
    link: /SEAStats
  - name: R Boot Camp
    link: /SEAStats/#rbootcamp
  - name: Mixed Models in R
    link: /SEAStats/#mixedmodelsinr
  - name: ggplot2 Basics
    link: /SEAStats/#ggplot2basics
  - name: Bayesian Mixed Models with brms
    link: /SEAStats/#bayesianmixedmodels
  - name: R for SAS Users
    link: /SEAStats/#rforsas
  - name: Other learning resources
    link: /SEAStats/#other-learning-resources
  - name: Archived course pages
    link: /SEAStats/#archived-course-and-workshop-pages

    
    
