# Setup
title:               SEAStats
url:                 https://qdread.github.io
baseurl:             /SEAstats

# About/contact
author:
  name:              Quentin Read
  url:               https://quentinread.com
  email:             quentin.read@usda.gov

markdown:            kramdown
remote_theme:        pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

github:
  repo:              https://github.com/qdread/SEAStats